package it.ads.activitiesmanager.model.entity;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * ActivityType generated by hbm2java
 */
@Entity
@Table(name = "ActivityType", catalog = "amdb", uniqueConstraints = @UniqueConstraint(columnNames = "T_NAME"))
public class ActivityType implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer typeId;
	private String TName;
	private Set<Activity> activities = new HashSet<Activity>(0);

	public ActivityType() {
	}

	public ActivityType(String TName) {
		this.TName = TName;
	}

	public ActivityType(String TName, Set<Activity> activities) {
		this.TName = TName;
		this.activities = activities;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "TYPE_ID", unique = true, nullable = false)
	public Integer getTypeId() {
		return this.typeId;
	}

	public void setTypeId(Integer typeId) {
		this.typeId = typeId;
	}

	@Column(name = "T_NAME", unique = true, nullable = false, length = 20)
	public String getTName() {
		return this.TName;
	}

	public void setTName(String TName) {
		this.TName = TName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "activityType")
	public Set<Activity> getActivities() {
		return this.activities;
	}

	public void setActivities(Set<Activity> activities) {
		this.activities = activities;
	}

}
