package it.ads.activitiesmanager.model.entity;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Activity generated by hbm2java
 */
@Entity
@Table(name = "Activity", catalog = "amdb")
public class Activity implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer activityId;
	private ActivityType activityType;
	private User user;
	private ActivityStatus activityStatus;
	private String AName;
	private String ADescription;

	public Activity() {
	}

	public Activity(ActivityType activityType, User user, ActivityStatus activityStatus, String AName,
			String ADescription) {
		this.activityType = activityType;
		this.user = user;
		this.activityStatus = activityStatus;
		this.AName = AName;
		this.ADescription = ADescription;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ACTIVITY_ID", unique = true, nullable = false)
	public Integer getActivityId() {
		return this.activityId;
	}

	public void setActivityId(Integer activityId) {
		this.activityId = activityId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "A_TYPE_ID", nullable = false)
	public ActivityType getActivityType() {
		return this.activityType;
	}

	public void setActivityType(ActivityType activityType) {
		this.activityType = activityType;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "A_USER_ID", nullable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "A_STATUS_ID", nullable = false)
	public ActivityStatus getActivityStatus() {
		return this.activityStatus;
	}

	public void setActivityStatus(ActivityStatus activityStatus) {
		this.activityStatus = activityStatus;
	}

	@Column(name = "A_NAME", nullable = false, length = 45)
	public String getAName() {
		return this.AName;
	}

	public void setAName(String AName) {
		this.AName = AName;
	}

	@Column(name = "A_DESCRIPTION", nullable = false, length = 500)
	public String getADescription() {
		return this.ADescription;
	}

	public void setADescription(String ADescription) {
		this.ADescription = ADescription;
	}

}
