package it.ads.activitiesmanager.model.entity;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * ActivityStatus generated by hbm2java
 */
@Entity
@Table(name = "ActivityStatus", catalog = "amdb", uniqueConstraints = @UniqueConstraint(columnNames = "S_NAME"))
public class ActivityStatus implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int statusId;
	private String SName;
	private Set<Activity> activities = new HashSet<Activity>(0);

	public ActivityStatus() {
	}

	public ActivityStatus(int statusId, String SName) {
		this.statusId = statusId;
		this.SName = SName;
	}

	public ActivityStatus(int statusId, String SName, Set<Activity> activities) {
		this.statusId = statusId;
		this.SName = SName;
		this.activities = activities;
	}

	@Id

	@Column(name = "STATUS_ID", unique = true, nullable = false)
	public int getStatusId() {
		return this.statusId;
	}

	public void setStatusId(int statusId) {
		this.statusId = statusId;
	}

	@Column(name = "S_NAME", unique = true, nullable = false, length = 20)
	public String getSName() {
		return this.SName;
	}

	public void setSName(String SName) {
		this.SName = SName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "activityStatus")
	public Set<Activity> getActivities() {
		return this.activities;
	}

	public void setActivities(Set<Activity> activities) {
		this.activities = activities;
	}

}
